### ISSUE TITLE
Interview partner finden!

### ISSUE THREAD

**Issue by yaroth** [yaroth/ch.bfh.bti7081.s2019.white#2]
Wer kennt jemanden, der/die auf die Zielgruppe((ambulant)patient) und/oder über die Krankheit (depression) ein Interview geben könnte?

**Comment by yaroth** [comment]
Unsere Nachbarin ist Psychiaterin. Sie könnte sicher etwas zu Depressionen erzählen.

**Comment by mullm** [comment]
Mein ehemaliger Mitbewohner ist gerade seine Masterarbeit in Psychologie am schreiben. Er könnte sicher auch Fragen beantworten.

**Comment by remohofmann** [comment]
Interview mit einer Person gemacht. kamen ein paar gute Punkte raus,
